const fs = require('fs');
const path = require('path');

const MAPS_DIR = path.join(__dirname, 'docs/curriculum/history/Maps');
const OVERLAYS_DIR = path.join(MAPS_DIR, 'overlays');

if (!fs.existsSync(OVERLAYS_DIR)) {
  fs.mkdirSync(OVERLAYS_DIR, { recursive: true });
}

// All batch B maps have 2816x1536 resolution according to file command
const WIDTH = 2816;
const HEIGHT = 1536;

const batchBMaps = [
  'map_006_roman_north_africa',
  'map_007_roman_egypt',
  'map_008_aksum_red_sea_trade',
  'map_009_egyptian_desert_monasticism',
  'map_010_garamantian_kingdom'
];

// Helper to escape XML
function escapeXml(unsafe) {
  if (!unsafe) return '';
  return unsafe.toString().replace(/[<>&'"]/g, function (c) {
    switch (c) {
      case '<': return '&lt;';
      case '>': return '&gt;';
      case '&': return '&amp;';
      case '\'': return '&apos;';
      case '"': return '&quot;';
    }
  });
}

function generateSvg(mapId, mapData) {
  let svg = `<!-- Generated by Jules, Phase 13, Batch B, ${new Date().toISOString().split('T')[0]} -->\n`;
  svg += `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${WIDTH} ${HEIGHT}" width="${WIDTH}" height="${HEIGHT}">\n`;

  // A generic coordinate mapping function since true lat/lon mapping without projection logic is hard.
  // We'll just generate centralized placeholders like in Batch A.

  // Regions
  let regions = mapData.provincial_boundaries || mapData.regions || mapData.garamantian_heartland ? [mapData.garamantian_heartland] : [];
  if (mapData.garamantian_heartland) {
      regions = [mapData.garamantian_heartland];
  } else if (mapData.provincial_boundaries) {
      regions = mapData.provincial_boundaries;
  }

  if (regions && regions.length > 0 && regions[0]) {
    svg += `  <g id="regions">\n`;
    regions.forEach((region, index) => {
      // Simplified central rectangles
      const x = 1000 + (index * 150);
      const y = 600 + (index * 50);
      const w = 300;
      const h = 200;

      let fill = "hsl(0, 0%, 50%)"; // default
      if (region.fill) {
         if (region.fill.includes('red')) fill = "hsl(0, 70%, 50%)";
         else if (region.fill.includes('orange')) fill = "hsl(30, 80%, 50%)";
         else if (region.fill.includes('green')) fill = "hsl(120, 60%, 50%)";
         else if (region.fill.includes('blue')) fill = "hsl(210, 60%, 50%)";
         else if (region.fill.includes('purple')) fill = "hsl(270, 60%, 50%)";
      }

      const id = region.province || region.region || `region-${index}`;
      const safeId = id.toLowerCase().replace(/[^a-z0-9]/g, '-');

      svg += `    <path id="${safeId}" d="M ${x} ${y} L ${x+w} ${y} L ${x+w} ${y+h} L ${x} ${y+h} Z" fill="${fill}" fill-opacity="0.3" stroke="${fill}" stroke-width="2" />\n`;

      const labelLines = region.label ? region.label.split('\\n') : [id];
      labelLines.forEach((line, i) => {
         svg += `    <text x="${x + w/2}" y="${y + h/2 + (i*30) - 15}" font-family="Inter, sans-serif" font-size="24" fill="#000" text-anchor="middle" font-weight="bold">${escapeXml(line)}</text>\n`;
      });
    });
    svg += `  </g>\n`;
  }

  // Routes
  let routes = mapData.routes || mapData.trade_routes || mapData.pilgrimage_routes || [];
  if (routes && routes.length > 0) {
    svg += `  <g id="routes">\n`;
    routes.forEach((route, index) => {
      const x1 = 1200 + (index * 50);
      const y1 = 500 + (index * 50);
      const x2 = 1500 + (index * 50);
      const y2 = 800 + (index * 50);
      const cx = (x1 + x2) / 2 + 100;
      const cy = (y1 + y2) / 2 - 100;

      let stroke = "hsl(45, 80%, 50%)"; // default gold
      if (route.style) {
         if (route.style.includes('red')) stroke = "hsl(0, 70%, 50%)";
         else if (route.style.includes('blue')) stroke = "hsl(210, 60%, 50%)";
         else if (route.style.includes('purple')) stroke = "hsl(270, 60%, 50%)";
         else if (route.style.includes('brown')) stroke = "hsl(30, 60%, 40%)";
         else if (route.style.includes('black')) stroke = "#000";
      }

      let dasharray = "0";
      if (route.style && route.style.includes('dashed')) dasharray = "10,10";
      if (route.style && route.style.includes('dotted')) dasharray = "4,4";

      const id = route.name || `route-${index}`;
      const safeId = id.toLowerCase().replace(/[^a-z0-9]/g, '-');

      svg += `    <path id="${safeId}" d="M ${x1} ${y1} Q ${cx} ${cy} ${x2} ${y2}" fill="none" stroke="${stroke}" stroke-width="4" stroke-dasharray="${dasharray}" />\n`;

      const labelText = route.name;
      svg += `    <text x="${cx}" y="${cy - 20}" font-family="Inter, sans-serif" font-size="20" fill="${stroke}" text-anchor="middle" font-weight="bold">${escapeXml(labelText)}</text>\n`;
    });
    svg += `  </g>\n`;
  }

  // Settlements / Cities / Markers
  let settlements = [];
  if (mapData.cities) settlements = settlements.concat(mapData.cities);
  if (mapData.monastic_sites) settlements = settlements.concat(mapData.monastic_sites);
  if (mapData.arabian_cities) settlements = settlements.concat(mapData.arabian_cities);
  if (mapData.coastal_cities) settlements = settlements.concat(mapData.coastal_cities);
  if (mapData.christian_sites) settlements = settlements.concat(mapData.christian_sites);

  if (settlements && settlements.length > 0) {
    svg += `  <g id="settlements">\n`;
    settlements.forEach((site, index) => {
      // Very rough distribution
      const cx = 1400 + ((index % 5) * 150) - 300;
      const cy = 600 + (Math.floor(index / 5) * 100);

      let fill = "#000";
      let isRect = false;
      let isCross = false;

      if (site.marker) {
         if (site.marker.includes('red')) fill = "hsl(0, 70%, 50%)";
         else if (site.marker.includes('orange')) fill = "hsl(30, 80%, 50%)";
         else if (site.marker.includes('green')) fill = "hsl(120, 60%, 50%)";
         else if (site.marker.includes('blue')) fill = "hsl(210, 60%, 50%)";
         else if (site.marker.includes('purple')) fill = "hsl(270, 60%, 50%)";
         else if (site.marker.includes('gold') || site.marker.includes('yellow')) fill = "hsl(45, 80%, 50%)";
         else if (site.marker.includes('brown')) fill = "hsl(30, 60%, 40%)";

         if (site.marker.includes('square')) isRect = true;
         if (site.marker.includes('cross')) isCross = true;
      }

      const id = site.name || `site-${index}`;
      const safeId = id.toLowerCase().replace(/[^a-z0-9]/g, '-');

      if (isCross) {
         svg += `    <path id="${safeId}" d="M ${cx-4} ${cy-10} L ${cx+4} ${cy-10} L ${cx+4} ${cy-4} L ${cx+10} ${cy-4} L ${cx+10} ${cy+4} L ${cx+4} ${cy+4} L ${cx+4} ${cy+12} L ${cx-4} ${cy+12} L ${cx-4} ${cy+4} L ${cx-10} ${cy+4} L ${cx-10} ${cy-4} L ${cx-4} ${cy-4} Z" fill="${fill}" stroke="black" stroke-width="1" />\n`;
      } else if (isRect) {
         svg += `    <rect id="${safeId}" x="${cx-8}" y="${cy-8}" width="16" height="16" fill="${fill}" stroke="black" stroke-width="1" />\n`;
      } else {
         svg += `    <circle id="${safeId}" cx="${cx}" cy="${cy}" r="6" fill="${fill}" stroke="black" stroke-width="1" />\n`;
      }

      let labelLines = site.label ? site.label.split('\\n') : [site.name];
      // Only take the first line or two to avoid clutter
      labelLines = labelLines.slice(0, 2);

      labelLines.forEach((line, i) => {
         svg += `    <text x="${cx}" y="${cy + 15 + (i*15)}" font-family="Inter, sans-serif" font-size="14" fill="#000" text-anchor="middle" font-weight="bold">${escapeXml(line)}</text>\n`;
      });
    });
    svg += `  </g>\n`;
  }

  svg += `</svg>\n`;
  return svg;
}

batchBMaps.forEach(mapId => {
  const mdPath = path.join(MAPS_DIR, `${mapId}.md`);
  if (!fs.existsSync(mdPath)) {
    console.log(`Skipping ${mapId}: markdown file not found.`);
    return;
  }

  const content = fs.readFileSync(mdPath, 'utf8');
  const jsonMatch = content.match(/\`\`\`json\n([\s\S]*?)\n\`\`\`/);

  if (jsonMatch && jsonMatch[1]) {
    try {
      const mapData = JSON.parse(jsonMatch[1]);
      const svg = generateSvg(mapId, mapData);

      // Zero-pad map number
      const mapNumStr = mapId.split('_')[1];
      const svgFileName = `map_${mapNumStr}_overlay.svg`;
      const svgPath = path.join(OVERLAYS_DIR, svgFileName);

      fs.writeFileSync(svgPath, svg);
      console.log(`Generated ${svgFileName}`);
    } catch (err) {
      console.error(`Error parsing JSON in ${mapId}.md:`, err);
    }
  } else {
    console.log(`No JSON block found in ${mapId}.md`);
  }
});

console.log('Batch B SVG generation complete.');
