DELETE FROM Glossary_Terms;
INSERT INTO Glossary_Terms (id, term, definition, category, related_chapter_ids) VALUES ('term_aksum', 'Aksum', 'An ancient kingdom located in northern Ethiopia and Eritrea, known for its monumental obelisks and early adoption of Christianity.', 'place', '["chapter_07","ch04","ch07"]');
INSERT INTO Glossary_Terms (id, term, definition, category, related_chapter_ids) VALUES ('term_carthage', 'Carthage', 'A major city in ancient North Africa, founded by Phoenicians, known for its trading empire and wars with Rome.', 'place', '["chapter_03","ch03","ch05","ch06","ch07"]');
INSERT INTO Glossary_Terms (id, term, definition, category, related_chapter_ids) VALUES ('term_bantu', 'Bantu', 'A major language family and group of peoples that migrated across Sub-Saharan Africa, shaping the demographic and cultural landscape.', 'concept', '["chapter_08","ch01","ch08","ch10"]');
INSERT INTO Glossary_Terms (id, term, definition, category, related_chapter_ids) VALUES ('term_cush', 'Cush', 'An ancient kingdom located south of Egypt in what is now Sudan, heavily influenced by and sometimes ruling over Egypt.', 'place', '["chapter_04","ch01","ch03","ch04","ch06","ch07","ch08"]');
INSERT INTO Glossary_Terms (id, term, definition, category, related_chapter_ids) VALUES ('term_numidia', 'Numidia', 'An ancient Berber kingdom in North Africa, allied with Rome and later becoming a Roman province.', 'place', '["chapter_03","ch03","ch05"]');
INSERT INTO Glossary_Terms (id, term, definition, category, related_chapter_ids) VALUES ('term_alexandria', 'Alexandria', 'A major Mediterranean port city in Egypt, known in antiquity for its great library and lighthouse, and as an early center of Christianity.', 'place', '["chapter_06","ch02","ch03","ch04","ch05","ch06","ch07","ch09"]');
INSERT INTO Glossary_Terms (id, term, definition, category, related_chapter_ids) VALUES ('term_phut', 'Phut', 'Biblical figure, traditionally associated with ancient Libya or the region west of Egypt.', 'person', '["chapter_03","ch01","ch03","ch05"]');
INSERT INTO Glossary_Terms (id, term, definition, category, related_chapter_ids) VALUES ('term_ethiopia', 'Ethiopia', 'A country in the Horn of Africa, home to one of the world''s oldest Christian churches and known for its rugged highlands and ancient history.', 'place', '["chapter_09","ch01","ch03","ch04","ch06","ch07","ch08","ch09","ch10"]');
