import fs from 'fs';
import path from 'path';

// This script reads the curriculum JSON data (generated by Jules)
// and generates a `db/seed_curriculum.sql` file that can be executed
// via Wrangler: `npx wrangler d1 execute learnlive-db-prod --local --file=./db/seed_curriculum.sql`

const CURRICULUM_DATA_DIR = path.join(process.cwd(), 'curriculum_data');
const OUTPUT_SQL_FILE = path.join(process.cwd(), 'db', 'seed_curriculum.sql');

interface Template {
    capacity_id: string;
    strand?: number;
    band?: number;
    cognitive_level: number | string; // Jules may output string names or integers
    variation_id: string;
    task_type: string;
    materials?: string | string[] | null;
    parent_prompt: string;
    success_condition: string;
    failure_condition?: string | null;
    reasoning_check: string;
    context_variants: string | Record<string, any>;
    requires_parent_primer?: boolean;
}

/**
 * Converts cognitive level from string name to integer.
 * Accepts both string names and raw integers.
 */
function normalizeCognitiveLevel(level: number | string): number {
    if (typeof level === 'number') return level;
    const map: Record<string, number> = {
        'encounter': 1,
        'execute': 2,
        'discern': 3,
        'own': 4,
    };
    const normalized = map[level.toLowerCase()];
    if (!normalized) {
        console.warn(`[SEED] Unknown cognitive level "${level}", defaulting to 1`);
        return 1;
    }
    return normalized;
}

/**
 * Normalizes the materials field — arrays are joined, objects are JSON-stringified,
 * strings are passed through.
 */
function normalizeMaterials(materials: string | string[] | null | undefined): string | null {
    if (!materials) return null;
    if (Array.isArray(materials)) return materials.join(', ');
    if (typeof materials === 'object') return JSON.stringify(materials);
    return materials;
}

/**
 * Normalizes context_variants — objects are JSON-stringified, strings are passed through.
 */
function normalizeContextVariants(cv: string | Record<string, any>): string {
    if (typeof cv === 'string') return cv;
    return JSON.stringify(cv);
}

/** Escapes single quotes for safe SQL insertion */
function safeString(str?: string | null): string {
    if (str === null || str === undefined) return 'NULL';
    return `'${str.replace(/'/g, "''")}'`;
}

function generateSQL() {
    let sql = `-- =============================================================================\n`;
    sql += `-- Learn Live — Curriculum Spine Seed Data\n`;
    sql += `-- Auto-generated from JSON template files\n`;
    sql += `-- =============================================================================\n\n`;

    // Base deletes to ensure idempotency
    sql += `DELETE FROM Constraint_Templates;\n`;
    sql += `DELETE FROM Capacity_Dependencies;\n`;
    sql += `DELETE FROM Capacities;\n`;
    sql += `DELETE FROM Strands;\n`;
    sql += `DELETE FROM Developmental_Bands;\n\n`;

    // 1. Seed Developmental Bands
    sql += `-- ── Developmental Bands ─────────────────────────────────────────────────────\n`;
    const bands = [
        { id: 'Band_0', name: 'Infant/Toddler', age_range: '0-3' },
        { id: 'Band_1', name: 'Early Childhood', age_range: '3-6' },
        { id: 'Band_2', name: 'Early Primary', age_range: '6-9' },
        { id: 'Band_3', name: 'Upper Primary', age_range: '9-12' },
        { id: 'Band_4', name: 'Middle School', age_range: '12-15' },
        { id: 'Band_5', name: 'High School', age_range: '15-18' }
    ];
    for (const b of bands) {
        sql += `INSERT INTO Developmental_Bands (id, name, age_range) VALUES ('${b.id}', '${b.name}', '${b.age_range}');\n`;
    }
    sql += `\n`;

    // 2. Seed Strands
    sql += `-- ── Strands ─────────────────────────────────────────────────────────────────\n`;
    const strands = [
        { id: 'Strand_1', name: 'Number & Quantity' },
        { id: 'Strand_2', name: 'Algebraic Thinking & Structure' },
        { id: 'Strand_3', name: 'Spatial Reasoning & Geometry' },
        { id: 'Strand_4', name: 'Data, Probability & Statistics' },
        { id: 'Strand_5', name: 'Mathematical Modeling & Systems' }
    ];
    for (const s of strands) {
        sql += `INSERT INTO Strands (id, name) VALUES ('${s.id}', '${s.name}');\n`;
    }
    sql += `\n`;

    // Ensure JSON directory exists so we don't crash before Jules runs
    if (!fs.existsSync(CURRICULUM_DATA_DIR)) {
        fs.mkdirSync(CURRICULUM_DATA_DIR, { recursive: true });
        console.log(`Created directory: ${CURRICULUM_DATA_DIR}`);
    }

    // 3. Process Jules JSON Files — first pass: extract unique capacities
    const files = fs.readdirSync(CURRICULUM_DATA_DIR).filter(f => f.endsWith('.json'));

    // Collect unique capacities from template data so we can seed the Capacities table
    const capacityMap = new Map<string, { strand_id: string; band_id: string; name: string }>();

    const allTemplates: { file: string; templates: Template[] }[] = [];

    for (const file of files) {
        console.log(`Processing file: ${file}`);
        const raw = fs.readFileSync(path.join(CURRICULUM_DATA_DIR, file), 'utf8');
        try {
            const templates: Template[] = JSON.parse(raw);
            allTemplates.push({ file, templates });

            for (const t of templates) {
                if (!capacityMap.has(t.capacity_id)) {
                    // Derive strand and band from the file name or template fields
                    const strandMatch = file.match(/strand_(\d+)/);
                    const strandNum = t.strand || (strandMatch ? parseInt(strandMatch[1]) : 1);
                    const bandMatch = file.match(/band_(\d+)/);
                    const bandNum = t.band || (bandMatch ? parseInt(bandMatch[1]) : 2);

                    capacityMap.set(t.capacity_id, {
                        strand_id: `Strand_${strandNum}`,
                        band_id: `Band_${bandNum}`,
                        name: t.capacity_id, // Will use capacity_id as name; can be enriched later
                    });
                }
            }
        } catch (e) {
            console.error(`Error parsing ${file}:`, e);
        }
    }

    // 3a. Seed Capacities
    sql += `-- ── Capacities (auto-extracted from templates) ──────────────────────────────\n`;
    for (const [id, cap] of capacityMap) {
        sql += `INSERT INTO Capacities (id, strand_id, band_id, name) VALUES ('${id}', '${cap.strand_id}', '${cap.band_id}', '${cap.name}');\n`;
    }
    sql += `\n`;

    // 3b. Seed Constraint Templates
    sql += `-- ── Constraint Templates ────────────────────────────────────────────────────\n`;

    if (allTemplates.length === 0) {
        console.log(`No JSON files found in ${CURRICULUM_DATA_DIR}. Skipping template SQL generation.`);
        sql += `-- (No JSON templates found during generation)\n`;
    } else {
        for (const { file, templates } of allTemplates) {
            sql += `-- Source: ${file}\n`;
            for (const t of templates) {
                const cogLevel = normalizeCognitiveLevel(t.cognitive_level);
                const id = `${t.capacity_id}_L${cogLevel}_${t.variation_id}`;
                const materials = normalizeMaterials(t.materials);
                const contextVariants = normalizeContextVariants(t.context_variants);

                sql += `INSERT INTO Constraint_Templates(
    id, capacity_id, cognitive_level, variation_id, task_type,
    materials, parent_prompt, success_condition, failure_condition,
    reasoning_check, context_variants, requires_parent_primer
) VALUES(
    ${safeString(id)}, ${safeString(t.capacity_id)}, ${cogLevel}, ${safeString(t.variation_id)}, ${safeString(t.task_type)},
    ${safeString(materials)}, ${safeString(t.parent_prompt)}, ${safeString(t.success_condition)}, ${safeString(t.failure_condition)},
    ${safeString(t.reasoning_check)}, ${safeString(contextVariants)}, ${t.requires_parent_primer ? 1 : 0}
);\n`;
            }
        }
    }

    fs.writeFileSync(OUTPUT_SQL_FILE, sql, 'utf8');
    console.log(`Successfully generated ${OUTPUT_SQL_FILE}`);
}

generateSQL();
