import fs from 'fs';
import path from 'path';

// This script reads the curriculum JSON data (generated by Jules)
// and generates a `db/seed_curriculum.sql` file that can be executed
// via Wrangler: `npx wrangler d1 execute learnlive-db-prod --local --file=./db/seed_curriculum.sql`

const CURRICULUM_DATA_DIR = path.join(process.cwd(), 'curriculum_data');
const OUTPUT_SQL_FILE = path.join(process.cwd(), 'db', 'seed_curriculum.sql');

interface Template {
    capacity_id: string;
    cognitive_level: number;
    variation_id: string;
    task_type: string;
    materials?: string | null;
    parent_prompt: string;
    success_condition: string;
    failure_condition?: string | null;
    reasoning_check: string;
    context_variants: string;
    requires_parent_primer?: boolean;
}

function generateSQL() {
    let sql = `-- =============================================================================\n`;
    sql += `-- Learn Live — Curriculum Spine Seed Data\n`;
    sql += `-- Auto-generated from JSON template files\n`;
    sql += `-- =============================================================================\n\n`;

    // Base deletes to ensure idempotency
    sql += `DELETE FROM Constraint_Templates;\n`;
    sql += `DELETE FROM Capacity_Dependencies;\n`;
    sql += `DELETE FROM Capacities;\n`;
    sql += `DELETE FROM Strands;\n`;
    sql += `DELETE FROM Developmental_Bands;\n\n`;

    // 1. Seed Developmental Bands
    sql += `-- ── Developmental Bands ─────────────────────────────────────────────────────\n`;
    const bands = [
        { id: 'Band_0', name: 'Infant/Toddler', age_range: '0-3' },
        { id: 'Band_1', name: 'Early Childhood', age_range: '3-6' },
        { id: 'Band_2', name: 'Early Primary', age_range: '6-9' },
        { id: 'Band_3', name: 'Upper Primary', age_range: '9-12' },
        { id: 'Band_4', name: 'Middle School', age_range: '12-15' },
        { id: 'Band_5', name: 'High School', age_range: '15-18' }
    ];
    for (const b of bands) {
        sql += `INSERT INTO Developmental_Bands (id, name, age_range) VALUES ('${b.id}', '${b.name}', '${b.age_range}');\n`;
    }
    sql += `\n`;

    // 2. Seed Strands
    sql += `-- ── Strands ─────────────────────────────────────────────────────────────────\n`;
    const strands = [
        { id: 'Strand_1', name: 'Number & Quantity' },
        { id: 'Strand_2', name: 'Algebraic Thinking & Structure' },
        { id: 'Strand_3', name: 'Spatial Reasoning & Geometry' },
        { id: 'Strand_4', name: 'Data, Probability & Statistics' },
        { id: 'Strand_5', name: 'Mathematical Modeling & Systems' }
    ];
    for (const s of strands) {
        sql += `INSERT INTO Strands (id, name) VALUES ('${s.id}', '${s.name}');\n`;
    }
    sql += `\n`;

    // Ensure JSON directory exists so we don't crash before Jules runs
    if (!fs.existsSync(CURRICULUM_DATA_DIR)) {
        fs.mkdirSync(CURRICULUM_DATA_DIR, { recursive: true });
        console.log(`Created directory: ${CURRICULUM_DATA_DIR}`);
    }

    // 3. Process Jules JSON Files
    sql += `-- ── Constraint Templates ────────────────────────────────────────────────────\n`;
    const files = fs.readdirSync(CURRICULUM_DATA_DIR).filter(f => f.endsWith('.json'));

    if (files.length === 0) {
        console.log(`No JSON files found in ${CURRICULUM_DATA_DIR}. Skipping template SQL generation.`);
        sql += `-- (No JSON templates found during generation)\n`;
    } else {
        for (const file of files) {
            console.log(`Processing file: ${file}`);
            const raw = fs.readFileSync(path.join(CURRICULUM_DATA_DIR, file), 'utf8');
            try {
                const templates: Template[] = JSON.parse(raw);
                for (const t of templates) {
                    const id = \`\${t.capacity_id}_L\${t.cognitive_level}_\${t.variation_id}\`;
          
          // Escape single quotes for SQL
          const safeString = (str?: string | null) => str ? \`'\${str.replace(/'/g, "''")}'\` : 'NULL';
          
          sql += `INSERT INTO Constraint_Templates(
                        id, capacity_id, cognitive_level, variation_id, task_type,
                        materials, parent_prompt, success_condition, failure_condition,
                        reasoning_check, context_variants, requires_parent_primer
                    ) VALUES(
                        '${id}', '${t.capacity_id}', ${ t.cognitive_level }, '${t.variation_id}', ${ safeString(t.task_type)
                },
            ${ safeString(t.materials) }, ${ safeString(t.parent_prompt) }, ${ safeString(t.success_condition) }, ${ safeString(t.failure_condition) },
            ${ safeString(t.reasoning_check) }, ${ safeString(t.context_variants) }, ${ t.requires_parent_primer ? 1 : 0 }
          ); \n`;
        }
      } catch (e) {
        console.error(`Error parsing ${ file }: `, e);
      }
    }
  }

  fs.writeFileSync(OUTPUT_SQL_FILE, sql, 'utf8');
  console.log(`Successfully generated ${ OUTPUT_SQL_FILE } `);
}

generateSQL();
