name = "learn-live"
main = "src/index.ts"
compatibility_date = "2024-03-25"
account_id = "4b9e1f0f3d5f50f35db086b8ae9431e1"

# Binding to D1 Database
[[d1_databases]]
binding = "DB"
database_name = "learnlive-db-prod"
database_id = "27043dbb-5aa2-4be3-93fc-97860fb7c158"

# Binding to R2 Bucket
[[r2_buckets]]
binding = "EVIDENCE_VAULT"
bucket_name = "learnlive-evidence-vault"

# We will need these bindings when we add Auth and Gemini Keys
# [vars]
# GEMINI_API_KEY = "placeholder"
